name: Build

on:
  push:
    branches:
      - last-working
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build on ${{ matrix.os }}
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
        run: |
          go mod download
          go build -trimpath -ldflags="-s -w" -o minio.exe .\cmd

      - name: Upload MinIO binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-minio
          path: minio.exe