name: Build

on:
  push:
    branches:
      - last-working
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4

      - name: Download Deps
        run: |
          go mod download
      
      - name: Build on ${{ matrix.os }}
        env:
          CGO_ENABLED: 0
        run: |
          go build -trimpath -ldflags="-s -w" -o minio.exe .

      - name: Upload MinIO binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-minio
          path: minio.exe

      - name: Test minio
        run: |
          ./minio.exe --version